INSERT INTO usuarios (id, nome, funcao, cpf, contato, foto, login, senha) VALUES (1,'Tácito','CEO','955.264.472.85','92 9-9999-9999',null,'tacito', '$2a$10$0yEvoqhIbxgkzMo7t9l35.nwGS53pM2zk1TLYD2MQkU7acTHx3K/.');
INSERT INTO grupos (id, nome, descricao) VALUES (1, 'ADMINISTRADOR', 'Administrador'), (2, 'USUARIO_AVANCADO','Usuário Avançado'), (3, 'USUARIO_COMUM','Usuário Comum'); 
INSERT INTO usuario_grupo (usuario_id, grupo_id) VALUES (1, 1);

INSERT INTO categoria_produtos (id, nome) VALUES (1, 'Porta'), (2, 'Janela'), (3, 'Fechadura');
INSERT INTO fornecedores (id, nome) VALUES (1, 'Acer'), (2, 'Samsung');

INSERT INTO tipos_vendas (id, descricao) VALUES (1, 'Olx'), (2, 'Face');

INSERT INTO bairros (nome,zona) VALUES ('Adrianópolis','Centro-Sul');
INSERT INTO bairros (nome,zona) VALUES ('Aleixo','Centro-Sul');
INSERT INTO bairros (nome,zona) VALUES ('Alvorada','Centro-Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Armando Mendes','Leste');
INSERT INTO bairros (nome,zona) VALUES ('Betânia','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Cachoeirinha','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Centro','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Chapada','Centro-Sul');
INSERT INTO bairros (nome,zona) VALUES ('Cidade de Deus','Norte');
INSERT INTO bairros (nome,zona) VALUES ('Cidade Nova','Norte');
INSERT INTO bairros (nome,zona) VALUES ('Colônia Antônio Aleixo','Leste');
INSERT INTO bairros (nome,zona) VALUES ('Colônia Oliveira Machado','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Colônia Santo Antônio','Norte');
INSERT INTO bairros (nome,zona) VALUES ('Colônia Terra Nova','Norte');
INSERT INTO bairros (nome,zona) VALUES ('Compensa','Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Coroado','Leste');
INSERT INTO bairros (nome,zona) VALUES ('Crespo','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Da Paz','Centro-Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Distrito Industrial I','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Distrito Industrial II','Leste');
INSERT INTO bairros (nome,zona) VALUES ('Dom Pedro','Centro-Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Educandos','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Flores','Centro-Sul');
INSERT INTO bairros (nome,zona) VALUES ('Gilberto Mestrinho','Leste'); 
INSERT INTO bairros (nome,zona) VALUES ('Glória','Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Japiim','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Jorge Teixeira','Leste');
INSERT INTO bairros (nome,zona) VALUES ('Lago Azul','Norte');
INSERT INTO bairros (nome,zona) VALUES ('Lírio do Vale','Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Mauazinho','Leste');
INSERT INTO bairros (nome,zona) VALUES ('Monte das Oliveiras','Norte');
INSERT INTO bairros (nome,zona) VALUES ('Morro da Liberdade','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Nossa Senhora Aparecida','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Nossa Senhora das Graças','Centro-Sul');
INSERT INTO bairros (nome,zona) VALUES ('Nova Cidade','Norte');
INSERT INTO bairros (nome,zona) VALUES ('Nova Esperança','Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Novo Aleixo','Norte');
INSERT INTO bairros (nome,zona) VALUES ('Novo Israel','Norte');
INSERT INTO bairros (nome,zona) VALUES ('Parque 10 de Novembro','Centro-Sul');
INSERT INTO bairros (nome,zona) VALUES ('Petrópolis','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Planalto','Centro-Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Ponta Negra','Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Praça 14 de Janeiro','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Presidente Vargas','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Puraquequara','Leste');
INSERT INTO bairros (nome,zona) VALUES ('Raiz','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Redençao','Centro-Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Santa Etelvina','Norte');
INSERT INTO bairros (nome,zona) VALUES ('Santa Luzia','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Santo Agostinho','Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Santo Antônio','Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Sao Francisco','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Sao Geraldo','Centro-Sul');
INSERT INTO bairros (nome,zona) VALUES ('Sao Jorge','Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Sao José Operário','Leste');
INSERT INTO bairros (nome,zona) VALUES ('Sao Lázaro','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Sao Raimundo','Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Tancredo Neves','Leste');
INSERT INTO bairros (nome,zona) VALUES ('Taruma','Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Taruma-Açu','Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Vila Buriti','Sul');
INSERT INTO bairros (nome,zona) VALUES ('Vila da Prata','Oeste');
INSERT INTO bairros (nome,zona) VALUES ('Zumbi dos Palmares','Leste');