INSERT INTO usuarios (id, nome, funcao, cpf, contato, foto, login, senha) VALUES (1,'T�cito','CEO','955.264.472.85','92 9-9999-9999',null,'tacito', '$2a$10$0yEvoqhIbxgkzMo7t9l35.nwGS53pM2zk1TLYD2MQkU7acTHx3K/.');
INSERT INTO grupos (id, nome, descricao) VALUES (1, 'ADMINISTRADOR', 'Administrador'), (2, 'USUARIO_AVANCADO','Usu�rio Avan�ado'), (3, 'USUARIO_COMUM','Usu�rio Comum'); 
INSERT INTO usuario_grupo (usuario_id, grupo_id) VALUES (1, 1);

INSERT INTO categoria_produtos (id, nome) VALUES (1, 'Porta'), (2, 'Janela'), (3, 'Fechadura');
INSERT INTO fornecedores (id, nome) VALUES (1, 'Acer'), (2, 'Samsung');

INSERT INTO tipos_vendas (id, descricao) VALUES (1, 'Olx'), (2, 'Face');

INSERT INTO bairros (id,nome,zona) VALUES (1,'Adrian�polis','CENTRO_SUL');
INSERT INTO bairros (id,nome,zona) VALUES (2,'Aleixo','CENTRO_SUL');
INSERT INTO bairros (id,nome,zona) VALUES (3,'Alvorada','CENTRO_OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (4,'Armando Mendes','LESTE');
INSERT INTO bairros (id,nome,zona) VALUES (5,'Bet�nia','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (6,'Cachoeirinha','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (7,'Centro','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (8,'Chapada','CENTRO_SUL');
INSERT INTO bairros (id,nome,zona) VALUES (9,'Cidade de Deus','NORTE');
INSERT INTO bairros (id,nome,zona) VALUES (10,'Cidade Nova','NORTE');
INSERT INTO bairros (id,nome,zona) VALUES (11,'Col�nia Ant�nio Aleixo','LESTE');
INSERT INTO bairros (id,nome,zona) VALUES (12,'Col�nia Oliveira Machado','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (13,'Col�nia Santo Ant�nio','NORTE');
INSERT INTO bairros (id,nome,zona) VALUES (14,'Col�nia Terra Nova','NORTE');
INSERT INTO bairros (id,nome,zona) VALUES (15,'Compensa','OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (16,'Coroado','LESTE');
INSERT INTO bairros (id,nome,zona) VALUES (17,'Crespo','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (18,'Da Paz','CENTRO_OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (19,'Distrito Industrial I','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (20,'Distrito Industrial II','LESTE');
INSERT INTO bairros (id,nome,zona) VALUES (21,'Dom Pedro','CENTRO_OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (22,'Educandos','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (23,'Flores','CENTRO_SUL');
INSERT INTO bairros (id,nome,zona) VALUES (24,'Gilberto Mestrinho','LESTE'); 
INSERT INTO bairros (id,nome,zona) VALUES (25,'Gl�ria','OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (26,'Japiim','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (27,'Jorge Teixeira','LESTE');
INSERT INTO bairros (id,nome,zona) VALUES (28,'Lago Azul','NORTE');
INSERT INTO bairros (id,nome,zona) VALUES (29,'L�rio do Vale','OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (30,'Mauazinho','LESTE');
INSERT INTO bairros (id,nome,zona) VALUES (31,'Monte das Oliveiras','NORTE');
INSERT INTO bairros (id,nome,zona) VALUES (32,'Morro da Liberdade','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (33,'Nossa Senhora Aparecida','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (34,'Nossa Senhora das Gra�as','CENTRO_SUL');
INSERT INTO bairros (id,nome,zona) VALUES (35,'Nova Cidade','NORTE');
INSERT INTO bairros (id,nome,zona) VALUES (36,'Nova Esperan�a','OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (37,'Novo Aleixo','NORTE');
INSERT INTO bairros (id,nome,zona) VALUES (38,'Novo Israel','NORTE');
INSERT INTO bairros (id,nome,zona) VALUES (39,'Parque 10 de Novembro','CENTRO_SUL');
INSERT INTO bairros (id,nome,zona) VALUES (40,'Petr�polis','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (41,'Planalto','CENTRO_OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (42,'Ponta Negra','OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (43,'Pra�a 14 de Janeiro','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (44,'Presidente Vargas','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (45,'Puraquequara','LESTE');
INSERT INTO bairros (id,nome,zona) VALUES (46,'Raiz','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (47,'Reden�ao','CENTRO_OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (48,'Santa Etelvina','NORTE');
INSERT INTO bairros (id,nome,zona) VALUES (49,'Santa Luzia','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (50,'Santo Agostinho','OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (51,'Santo Ant�nio','OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (52,'Sao Francisco','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (53,'Sao Geraldo','CENTRO_SUL');
INSERT INTO bairros (id,nome,zona) VALUES (54,'Sao Jorge','OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (55,'Sao Jos� Oper�rio','LESTE');
INSERT INTO bairros (id,nome,zona) VALUES (56,'Sao L�zaro','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (57,'Sao Raimundo','OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (58,'Tancredo Neves','LESTE');
INSERT INTO bairros (id,nome,zona) VALUES (59,'Taruma','OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (60,'Taruma-A�u','OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (61,'Vila Buriti','SUL');
INSERT INTO bairros (id,nome,zona) VALUES (62,'Vila da Prata','OESTE');
INSERT INTO bairros (id,nome,zona) VALUES (63,'Zumbi dos Palmares','LESTE');