INSERT INTO usuarios (id, nome, funcao, cpf, contato, foto, login, senha) VALUES (1,'Tácito','CEO','955.264.472.85','92 9-9999-9999',null,'tacito', '$2a$10$0yEvoqhIbxgkzMo7t9l35.nwGS53pM2zk1TLYD2MQkU7acTHx3K/.');
INSERT INTO grupos (id, nome, descricao) VALUES (1, 'ADMINISTRADOR', 'Administrador'), (2, 'USUARIO_AVANCADO','Usuário Avançado'), (3, 'USUARIO_COMUM','Usuário Comum'); 
INSERT INTO usuario_grupo (usuario_id, grupo_id) VALUES (1, 1);

INSERT INTO categoria_produtos (id, nome) VALUES (1, 'Porta'), (2, 'Janela'), (3, 'Fechadura');
INSERT INTO fornecedores (id, nome) VALUES (1, 'Acer'), (2, 'Samsung');

INSERT INTO tipos_vendas (id, descricao) VALUES (1, 'Olx'), (2, 'Face');

INSERT INTO bairros(id,nome,zona) VALUES (1,'Adrianápolis','CENTRO_SUL');
INSERT INTO bairros(id,nome,zona) VALUES (2,'Aleixo','CENTRO_SUL');
INSERT INTO bairros(id,nome,zona) VALUES (3,'Alvorada','CENTRO_OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (4,'Armando Mendes','LESTE');
INSERT INTO bairros(id,nome,zona) VALUES (5,'Betânia','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (6,'Cachoeirinha','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (7,'Centro','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (8,'Chapada','CENTRO_SUL');
INSERT INTO bairros(id,nome,zona) VALUES (9,'Cidade de Deus','NORTE');
INSERT INTO bairros(id,nome,zona) VALUES (10,'Cidade Nova','NORTE');
INSERT INTO bairros(id,nome,zona) VALUES (11,'Colônia Antônio Aleixo','LESTE');
INSERT INTO bairros(id,nome,zona) VALUES (12,'Colônia Oliveira Machado','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (13,'Colônia Santo Antônio','NORTE');
INSERT INTO bairros(id,nome,zona) VALUES (14,'Colônia Terra Nova','NORTE');
INSERT INTO bairros(id,nome,zona) VALUES (15,'Compensa','OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (16,'Coroado','LESTE');
INSERT INTO bairros(id,nome,zona) VALUES (17,'Crespo','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (18,'Da Paz','CENTRO_OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (19,'Distrito Industrial I','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (20,'Distrito Industrial II','LESTE');
INSERT INTO bairros(id,nome,zona) VALUES (21,'Dom Pedro','CENTRO_OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (22,'Educandos','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (23,'Flores','CENTRO_SUL');
INSERT INTO bairros(id,nome,zona) VALUES (24,'Gilberto Mestrinho','LESTE');
INSERT INTO bairros(id,nome,zona) VALUES (25,'Glória','OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (26,'Japiim','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (27,'Jorge Teixeira','LESTE');
INSERT INTO bairros(id,nome,zona) VALUES (28,'Lago Azul','NORTE');
INSERT INTO bairros(id,nome,zona) VALUES (29,'Lírio do Vale','OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (30,'Mauazinho','LESTE');
INSERT INTO bairros(id,nome,zona) VALUES (31,'Monte das Oliveiras','NORTE');
INSERT INTO bairros(id,nome,zona) VALUES (32,'Morro da Liberdade','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (33,'Nossa Senhora Aparecida','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (34,'Nossa Senhora das Graças','CENTRO_SUL');
INSERT INTO bairros(id,nome,zona) VALUES (35,'Nova Cidade','NORTE');
INSERT INTO bairros(id,nome,zona) VALUES (36,'Nova Esperança','OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (37,'Novo Aleixo','NORTE');
INSERT INTO bairros(id,nome,zona) VALUES (38,'Novo Israel','NORTE');
INSERT INTO bairros(id,nome,zona) VALUES (39,'Parque 10 de Novembro','CENTRO_SUL');
INSERT INTO bairros(id,nome,zona) VALUES (40,'Petrópolis','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (41,'Planalto','CENTRO_OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (42,'Ponta Negra','OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (43,'Praça 14 de Janeiro','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (44,'Presidente Vargas','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (45,'Puraquequara','LESTE');
INSERT INTO bairros(id,nome,zona) VALUES (46,'Raiz','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (47,'Redençao','CENTRO_OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (48,'Santa Etelvina','NORTE');
INSERT INTO bairros(id,nome,zona) VALUES (49,'Santa Luzia','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (50,'Santo Agostinho','OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (51,'Santo Antônio','OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (52,'Sao Francisco','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (53,'Sao Geraldo','CENTRO_SUL');
INSERT INTO bairros(id,nome,zona) VALUES (54,'Sao Jorge','OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (55,'Sao José Operário','LESTE');
INSERT INTO bairros(id,nome,zona) VALUES (56,'Sao Lázaro','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (57,'Sao Raimundo','OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (58,'Tancredo Neves','LESTE');
INSERT INTO bairros(id,nome,zona) VALUES (59,'Taruma','OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (60,'Taruma-Açu','OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (61,'Vila Buriti','SUL');
INSERT INTO bairros(id,nome,zona) VALUES (62,'Vila da Prata','OESTE');
INSERT INTO bairros(id,nome,zona) VALUES (63,'Zumbi dos Palmares','LESTE');
INSERT INTO bairros(id,nome,zona) VALUES (64,'Não Informado','NORTE');

INSERT INTO tipos_lancamentos(id,descricao,origem) VALUES (42,'Receitas',1);
INSERT INTO tipos_lancamentos(id,descricao,origem) VALUES (40,'Custos',0);
INSERT INTO tipos_lancamentos(id,descricao,origem) VALUES (38,'Despesa fixa',0);
INSERT INTO tipos_lancamentos(id,descricao,origem) VALUES (39,'Despesa variável',0);
INSERT INTO tipos_lancamentos(id,descricao,origem) VALUES (41,'Investimentos',0);

INSERT INTO destino_lancamentos(id,descricao) VALUES (43,'Empresa');
INSERT INTO destino_lancamentos(id,descricao) VALUES (45,'Nilton Dantas');
INSERT INTO destino_lancamentos(id,descricao) VALUES (44,'Tiago Dantas');
INSERT INTO destino_lancamentos(id,descricao) VALUES (46,'Risonildo Dantas');
INSERT INTO destino_lancamentos(id,descricao) VALUES (47,'Tácito Dantas');
INSERT INTO destino_lancamentos(id,descricao) VALUES (35913,'Adriana');

INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (176,'Água',43,38);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (177,'Luz',43,38);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (37565,'Aporte',47,42);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (180,'Aluguel',43,38);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (183,'Manutenção de Veículos',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (186,'Manutenção de Equipamentos',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (185,'Despesas com alimentação e mantimentos',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (190,'Aquisição de bens e equipamentos',43,40);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25832,'Avarias',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25833,'Combustível',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25834,'Custos e viagens a negócios',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25836,'Despesas com saúde',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25837,'Empréstimos',43,41);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25838,'Frete de veículos',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25839,'Impostos',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25840,'Limpeza e serviços gerais',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25841,'Mão de obra com entregas',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25842,'Mão de obra em aduelas e alisares',43,40);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25843,'Material e serviço de construção',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25844,'Material indireto',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25845,'Material para acabamento em aduelas e alisares',43,40);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25846,'Material para serviços em MDF',43,40);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25847,'Material para acabamento em portas',43,40);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25848,'Material para serviços em vidro',43,40);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25849,'Material para uso direto',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25850,'Outras receitas',43,42);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25851,'Propaganda e marketing',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25853,'Segurança',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25854,'Serviço de manutenção em geral',43,39);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (178,'Telefone, internet e informática',43,38);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25855,'Transporte',43,38);
INSERT INTO categoria_lancamentos(id,nome,destinolancamento_id,tipolancamento_id) VALUES (25835,'Salários  / Décimo / Férias / Bônus / PLR',43,40);
